// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsESMJ4mG236bF8ezT69SElSer4qbmXTs',
    appId: '1:946013816903:web:4caeb4ffb8afef1ae04962',
    messagingSenderId: '946013816903',
    projectId: 'vetbridge-2d33e',
    authDomain: 'vetbridge-2d33e.firebaseapp.com',
    storageBucket: 'vetbridge-2d33e.firebasestorage.app',
    measurementId: 'G-B2YLVZML6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClF_23D3PiRI9149RBqi4jjEtwzuQQbo4',
    appId: '1:946013816903:android:babb917b724d5112e04962',
    messagingSenderId: '946013816903',
    projectId: 'vetbridge-2d33e',
    storageBucket: 'vetbridge-2d33e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIJdIDuYW83ztY-d4e2HWY2gyEoeT9XA',
    appId: '1:946013816903:ios:1f075c7d04dc1ac9e04962',
    messagingSenderId: '946013816903',
    projectId: 'vetbridge-2d33e',
    storageBucket: 'vetbridge-2d33e.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIJdIDuYW83ztY-d4e2HWY2gyEoeT9XA',
    appId: '1:946013816903:ios:1f075c7d04dc1ac9e04962',
    messagingSenderId: '946013816903',
    projectId: 'vetbridge-2d33e',
    storageBucket: 'vetbridge-2d33e.firebasestorage.app',
    iosBundleId: 'com.example.sprint2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsESMJ4mG236bF8ezT69SElSer4qbmXTs',
    appId: '1:946013816903:web:37b3453c6fc9b2f3e04962',
    messagingSenderId: '946013816903',
    projectId: 'vetbridge-2d33e',
    authDomain: 'vetbridge-2d33e.firebaseapp.com',
    storageBucket: 'vetbridge-2d33e.firebasestorage.app',
    measurementId: 'G-LQY05S2KXB',
  );
}
